### ISSUE TITLE
[Bugs] six bugs: crashes, attribute grabbing broken

### ISSUE THREAD

**Issue by Yakibomb** [rafradek/sigsegv-mvm#10]
1. **@f@filter_name@entity** crashes server
2. Adding an attribute that doesn't exist crashes server, i.e.:
- **"OnTrigger" "!activator,$AddPlayerAttribute,*firing speed bonus*|2,0,-1"**
- Where '*firing speed bonus*' doesn't exist (actual attribute is *fire rate bonus*)
3. Can't grab attributes (player or weapon) from Expression "*attribute( player or item, attribute name )*"
- This Expression doesn't spit out a float, integer or string, at all
5. Can't grab attributes from weapons (custom, vanilla/stock, etc) using **$GetItemAttribute**
6. **sig_test_expression** doesn't work in console or chat
~~7. **$filter_sendprop** seems to be broken and doesn't filter values anymore (worked about a week ago)~~

**Comment by Yakibomb** [comment]
My bad, $filter_sendprop *is* **working**. I messed up on with a keyvalue.

**Comment by Yakibomb** [comment]
Oh, I deleted everything under the filter_multi I was using, including the $filter_sendprops. Still testing.

**Comment by rafradek** [comment]
Should all be fixed. Also do note that text in expressions must be enclosed in single quotes so the correct way would be attribute( player or item, 'fire rate bonus').
For testing expressions use sig_expression command

**Comment by Yakibomb** [comment]
Awesome. Thanks raf! I'll be updating the wiki shortly with your new info.
