### ISSUE TITLE
[Bugs] $filter_sendprop < and > broken, Extended Upgrades' "RequiredWeapon" crashes

### ISSUE THREAD

**Issue by Yakibomb** [rafradek/sigsegv-mvm#11]
- Extended Upgrades' "**RequiredWeapons**" crashes server upon opening menu that features it
- **$filter_sendprop** keyvalue **$compare** "greater than" "less than" and the like do not compare.
-- however, "equal" works in all cases.
-- unsure about $filter_variable and other filters
-- Wiki claims that $compare is "equal" by default. It is not true.
- If Extended Upgrades upgrade goes over a threshold (i.e. 30+) and refund is executed, buffer net overflow happens and client disconnects.
- Unsure how to grab item attribute by name using Expression "$$=attribute( _item name_ , 'attribute name' )", it does not take single quotes or no quotes.
-- Note: I have only used !activator, which works

**Comment by rafradek** [comment]
hope all is fixed now.
Also, in order to read an item attribute you would have to use something like attribute( playeritembyname(!activator, 'item name') , 'attribute name' )

**Comment by Yakibomb** [comment]
I actually hadn't been able to get what you suggested to work. If I usually if I do `sig_expression` it would give me the right variable but this time, it doesn't give me anything.

**Comment by Yakibomb** [comment]
And it works. Idk what I was doing wrong!
