### ISSUE TITLE
[BUG] ERROR being spammed when spawning in func_forcefield

### ISSUE THREAD

**Issue by SargentoMesa** [rafradek/sigsegv-mvm#113]
"ERROR:  Can't draw studio model models/weapons/w_models/w_rocket.mdl because CBaseEntiy is not derived from C_BaseAnimating"
I have no idea if this fixable or not, thought itd be worth reporting

**Comment by mtxfellen** [comment]
Set `rendermode 10` on the brush if you're spawning it with pt.
