### ISSUE TITLE
[Suggestion] Attribute "custom item model" using similar code to $SetModelOverride

### ISSUE THREAD

**Issue by Yakibomb** [rafradek/sigsegv-mvm#12]
The attribute `custom item model` seems to add a `tf_wearable` to the player instead of outright replacing the model.

I noticed this trying to get the Pyro's rocketpack to work on the Engineer. The rocketpack uses a combination of a weapon model and tf_wearable to animate the rocketpack. I was trying to filter out the tf_wearable to change it a custom model to fit the Engineer.

However, because the `custom item model` model and the rocketpack wearable are both the same netprop `m_iItemDefinitionIndex`, (the ID for each item under items_game.txt) it was hard to filter them out to change them.

My solution for this was not using `custom item model`, and instead replacing the weapon model by filtering it by the weapon's `m_iItemDefinitionIndex` every time the player respawns. Then firing input `$SetModelOverride`.
This works great because it fixes the shadows and the tf_wearable/rocketpack being the same Item ID.

Other things I noticed with "custom item model":
- The invisible weapon still shows shadows
- The replaced weapon model outlines don't show up anymore if it has glow outlines (did before but was fixed)
- New model shows up as a `tf_wearable`, with `m_iItemDefinitionIndex` set to -1.
- The custom item model still shows up during taunts

If I could propose a solution to the above problem... would be to add an attribute to replace or add an extra wearable (tf_wearable) to the player? Or, something more extensive could be to use similar code to `$SetModelOverride` to get the model to change, instead of adding the new tf_wearable to replace the visuals of the model.

**Comment by rafradek** [comment]
custom item model uses a wearable because using model overrides break first person animations

**Comment by Yakibomb** [comment]
Ah, I haven't considered that. Was testing all my stuff third-person mode so I hadn't thought about it. No worries then!

Thanks raf
