### ISSUE TITLE
bug?/request? - 10mvm compatibility 

### ISSUE THREAD

**Issue by Gnomesenpai** [rafradek/sigsegv-mvm#13]
Hello, 

We are currently running this alongside 10mvm and while 10 people can connect to the server only 6 can join red, is this a bug or intended? if so can we have a variable to override this?

Thanks!

**Comment by Seelpit** [comment]
Hi,
6 red players is the standard for MvM. This should either be changed on the server itself, or by adding the related keyvalue in the popfile you are currently running:
`MaxRedPlayers 10`
inside of
`WaveSchedule{ }`

Hope this helps!

**Comment by rafradek** [comment]
You need to set sig_mvm_red_team_max_players convar to 10 and remove the 10mvm plugin

**Comment by Gnomesenpai** [comment]
We have increased the slot count to 16, removed the 10mvm plugin but still are hitting a cap at 7 players now, any suggestions?

**Comment by rafradek** [comment]
Yeah it appears that the value above 10 will not work correctly, needs to be fixed soon

**Comment by Gnomesenpai** [comment]
Okay, i will keep this open and once their is movement on your side i can re-test :)

**Comment by rafradek** [comment]
It might be fixed now
