### ISSUE TITLE
Weapon name isn't shown properly in Extended Upgrade Menu

### ISSUE THREAD

**Issue by CallItTrue** [rafradek/sigsegv-mvm#132]
Version: 20240927 and newer.
can't see weapon name in menu even though there were translated in the resource/tf_schinese file.
e.g. "TF_DS_DumpsterDevice"                "乞丐的火箭筒"

![6bede1419fd472ec02cf04cd0aa42c64](https://github.com/user-attachments/assets/4bb85c24-8f4d-420d-960e-92d5fa0df4e3)
![afcbdd04868b20a02126a0df507d05d4](https://github.com/user-attachments/assets/0ea8dc42-4bf4-43fe-ba88-92d6dca8dc35)
![703b524903ddb09105b1d0734a25d1e0](https://github.com/user-attachments/assets/8ea3a284-5abb-4a74-93b4-a3a2c8ccc1c9)
![b777527401e22c73274648c59f9d7760](https://github.com/user-attachments/assets/5bae1ef4-a402-42f8-999a-96c9c534487c)
![bc6e376f35b88c4952205e5de0a90409](https://github.com/user-attachments/assets/7bbbc88b-8f66-4200-8a27-89633229e359)

**Comment by rafradek** [comment]
It will be fixed. However, this was caused because of the line using unicode instead of ucs-2 character (the offending char is 锇): "TF_TournamentMedal_Osmium_Ordinance_Bohrium"			"锇金条例 𬭛金克星 2024"

**Comment by CallItTrue** [comment]
deleted those lines and it worked for now.
btw "Frying Pan" is still in English.
