### ISSUE TITLE
Join Team Blue not working

### ISSUE THREAD

**Issue by Gnomesenpai** [rafradek/sigsegv-mvm#14]
Hello, 

When in spectator and doing the command "jointeam blue" in console it pushes you onto red team and does not allow for you to join blue even with the jointeam blue set to 1. sig_mvm_jointeam_blue_allow_force does force players onto blue when enabled. is their specific in game commands for this or is it broken?

 

Test server: 136.243.152.116:27032

all users should be able to join blue, it is not limited to admins only.

**Comment by rafradek** [comment]
I joined the server, typed jointeam blue in console and it worked?

**Comment by Gnomesenpai** [comment]
Was that done from red team or spectator? Ill give it a try again tonight and report back

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rafradek** [comment]
It appears to work when done in both ways, but maybe its because i am alone
