### ISSUE TITLE
More than 10 on red

### ISSUE THREAD

**Issue by Gnomesenpai** [rafradek/sigsegv-mvm#15]
Hello,

So the latest version of the plugin is allowing more than 10 people to join the server, but even setting the following value to 16 it does not let more than 10 people on red. Is this a bug or do more things need changing/other plugins?

sig_mvm_red_team_max_players    "16"
sig_etc_extra_player_slots 1
sig_etc_extra_player_slots_count 64

**Comment by rafradek** [comment]
Yeah, the workaround for now should be to type jointeam red command in console

**Comment by Gnomesenpai** [comment]
Hello,

I tried that and it does not work once there is 10 players on red.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rafradek** [comment]
yeah i can try to investigate because i tried jointeam red in console and it worked for me

**Comment by Gnomesenpai** [comment]
Yeah it works fine when there is less than 10 players, but hitting the issue after 10, we had 12 in the server but only 10 could be in red.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rafradek** [comment]
could you provide the list of plugins you are using?

**Comment by Gnomesenpai** [comment]
Sure, when im home ill print the list

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rafradek** [comment]
Also the convars in sigsegv_convars.cfg

**Comment by rafradek** [comment]
Bump
