### ISSUE TITLE
Server crashes when applying `custom item model` or `custom view model` to a weapon entity.

### ISSUE THREAD

**Issue by HotoCocoaco** [rafradek/sigsegv-mvm#18]
Using tf2attributes:
```
int wep = SpawnWeapon(client, blablabla.....);  // wep is the spawned weapon's entity index.
if (IsValidEntity(wep))
{
  TF2Attrib_SetFromStringValue(wep, "custom item model", "blablabla.mdl");
}
```

crash log of `custom item model`: https://crash.limetech.org/isvk5sxt3omc
crash log of `custom view model`: https://crash.limetech.org/wmbtetgsh6oh

I am pretty sure both models are precached.

**Comment by rafradek** [comment]
Maybe with new update this is fixed

**Comment by HotoCocoaco** [comment]
> Maybe with new update this is fixed

Good news, no crash.
Bad news, attributes not working. Nothing happens after setting attributes to the weapon entity. Nor the weapon model neither the arm model changes.
`WeDidIt` is there so the code should be running smoothly.

```
#define BLADEMODEL "models/someblade.mdl"
#define ARMMODEL "models/somearm.mdl"

public void OnPluginStart()
{
  RegAdminCmd("sm_doweapon", _DoWeapon, ADMFLAG_CHEATS);
}

public void OnMapStart()
{
  PrecacheModel(BLADEMODEL);
  PrecacheModel(ARMMODEL);
}

Action _DoWeapon(int client, int args)
{
  int wep = SpawnWeapon(client, "tf_weapon_club", 423, 6, 6, "2 ; 3");
  TF2Attrib_SetFromStringValue(wep, "custom item model", BLADEMODEL);
  TF2Attrib_SetFromStringValue(wep, "custom view model", ARMMODEL);
  ReplyToCommand(client, "WeDidIt");
  return Plugin_Continue;
}
```

**Comment by rafradek** [comment]
You have 2 options:
1. Update TF2Attributes to the newest version
2. Set the attributes before the item is given to player
