### ISSUE TITLE
Restrict extra slots to bots only?

### ISSUE THREAD

**Issue by throwaway47777** [rafradek/sigsegv-mvm#21]
Is it possible to restrict the extra slots for bots only? If not, would probably just go with the route of filling up the server with bots up to 64 then kicking all bots from 32 and under.

**Comment by rafradek** [comment]
yes, all you have to do is to set sig_etc_extra_player_slots_allow_bots 1  in sigsegv_convars.cfg,

**Comment by throwaway47777** [comment]
> sig_etc_extra_player_slots_allow_bots 1

thanks, thought it was only for allowing bots to use the extra slots not also restrict.

**Comment by rafradek** [comment]
This is assuming sig_etc_extra_player_slots_allow_players is set to 0 (It is set to 0 by default)

**Comment by throwaway47777** [comment]
> sig_etc_extra_player_slots_allow_players

Did not see that anywhere in the cfgs, thanks again.
