### ISSUE TITLE
Extension started crashing server after 07/25/23 update

### ISSUE THREAD

**Issue by saxybois** [rafradek/sigsegv-mvm#23]
Crashlogs:
https://crash.limetech.org/3f4mvzc55ant
https://crash.limetech.org/nq6tajioill7

SourceMod version: 1.11.0.6934

**Comment by Oplkill** [comment]
The same crash even with latest dev sourcemod

**Comment by Oplkill** [comment]
After new extension update crashes fixed. Now its works well, thanks.

**Comment by saxybois** [comment]
Yeah, after updating the extension crashes stopped happening, closing this topic
