### ISSUE TITLE
CustomWeapon inherits ItemAttributes set in mission population files if they use the same OriginalItemName as the ItemName defined in the ItemAttributes block

### ISSUE THREAD

**Issue by Whurrhurr** [rafradek/sigsegv-mvm#27]
this can be seen on Mobocracy, The Harvester uses "upgradeable TF_WEAPON_FIREAXE" as a base, and shows up as "models/weapons/c_models/c_fireaxe_pyro/c_fireaxe_pyro_orange.mdl" instead of "models/weapons/c_models/c_scythe/c_scythe.mdl" because there is an ItemAttributes block that gives any "upgradeable TF_WEAPON_FIREAXE" the orange fireaxe model. before, CustomWeapon did not inherit any ItemAttributes block that are set in the mission itself, so now on Mobocracy, The Harvester shows up as an orange fire axe because it inherits the attributes in the upgradeable TF_WEAPON_FIREAXE ItemAttributes block. this is not intentional and breaks the CustomWeapon's appearance.

giving people a way to prevent their CustomWeapon from inheriting these ItemAttributes blocks would be appreciated.

**Comment by rafradek** [comment]
Hope its fixed
