### ISSUE TITLE
FF2:R hale overheal issue with sig_attr_custom setting

### ISSUE THREAD

**Issue by TheGreatWeegee** [rafradek/sigsegv-mvm#28]
when _sig_attr_custom_  cvar is on, hales upon spawning on FF2: Rewrite either gain a slight/big overheal which quickly decreases, or they spawn without a portion of their HP, happens on all hales, even those that have default abilities

downloaded latest release of both FF2:Rewrite and this extension, and this keeps happening
don't know if any other plugin causes this, but without this setting on (tried both disabling the setting and uninstalling the extension), bosses spawn as usual with proper HP settings

don't know if this issue is related to the extension, but if this is possible to fix - many thanks

**Comment by rafradek** [comment]
added sig_attr_speed_health_ammo_recalculate convar, you can turn it off to stop this behavior
