### ISSUE TITLE
Clients crash upon refunding upgrades with certain attributes

### ISSUE THREAD

**Issue by StardustSpie** [rafradek/sigsegv-mvm#30]
When making a custom upgrade, clients may crash if someone refunds with certain attributes. This affects the following attributes that i know of:
> scattergun has knockback
> radial cond
Im unsure if this is an issue on my end, but i highly doubt it

Clip below demonstrates me buying an upgrade with radial cond attribute

https://github.com/rafradek/sigsegv-mvm/assets/107283301/9ed8ee03-7c5c-4fa7-92c7-68e896a78bde

**Comment by rafradek** [comment]
should be fixed
