### ISSUE TITLE
[Bug] Area Portals are messed up and occlude units you can see through area portals when you are outside the area portal they are inside of

### ISSUE THREAD

**Issue by Whurrhurr** [rafradek/sigsegv-mvm#31]
![image](https://github.com/rafradek/sigsegv-mvm/assets/33162051/5be3195a-3e70-4991-85f2-7fc6a8f62e58)

there is a teleporter, large health kit and a large ammo pack in here, i can't see them because they are being hidden.

**Comment by rafradek** [comment]
Is there a reliable way to trigger this?

**Comment by Alex-gnzl** [comment]
Also experiencing this. Can't produce reliably, but it tends to happen pretty often near spawn on mvm_coaltown

**Comment by rafradek** [comment]
Should be fixed in 0f6fa5
