### ISSUE TITLE
[Bug] failing a wave that uses bots with UseHumanAnimations or UseCustomModel causes robots to have invisible playermodels

### ISSUE THREAD

**Issue by Whurrhurr** [rafradek/sigsegv-mvm#38]
title, if you fail the wave with let's say, 6 robots active all either using UseHumanAnimations or UseCustomModel, there will be 6 robots that will have invisible playermodels. what seems to be happening is that both of these KVs do not restore the original playermodel upon wave loss, it's also slot ID-specific, so if bot 20 gets this bug, any other time bot 20 spawns, they will be invisible, even if they spawn as a bot with UseHumanAnimations or UseCustomModel. this issue is most noticeable in Bauernhof, as all robots in it use UseCustomModel and failing at any point is going to result in people dying to "invisible zombies"

**Comment by rafradek** [comment]
This should be fixed
