### ISSUE TITLE
Add "sig_attr_display 0" to sigsegv_convars_pvp.cfg

### ISSUE THREAD

**Issue by aarmastah** [rafradek/sigsegv-mvm#47]
Hello! I'd like to request a new cvar to enable/disable the inspect menu that appears when using the full package (package_linux.tar.gz). For reference, I'm currently using the latest release (20231209 package_linux.tar.gz) on Ubuntu 22.04 on my servers, and said inspect menu looks like this (circled in red):

![image](https://github.com/rafradek/sigsegv-mvm/assets/1887380/6e2ddc84-8f33-409a-997e-ebe22147912e)

I have a repo set up to automate deploying TF2 servers and I'd like to have the ability to disable this inspect menu on non-MvM maps, so a cvar to change it would be amazing!

**Comment by aarmastah** [comment]
> I think you can already do this using this ConVar:
> 
> > sig_attr_display	"1"		// Enable displaying custom attributes on the right side of the screen

Perfect! Maybe the issue now isn't that we need a new cvar, but that sig_attr_display "0" should be present in sigsegv_pvp.cfg by default?

**Comment by rafradek** [comment]
The inspect text should no longer appear in non mvm gamemodes when item/player has no custom attributes
