### ISSUE TITLE
Is extension planned to be updated for 64-bit TF2 in far future or nah?

### ISSUE THREAD

**Issue by KaelaSavia** [rafradek/sigsegv-mvm#48]
Just a small question!

**Comment by talascio** [comment]
I cannot speak for raf, but I will say many of the MvM-specific/popfile features are currently being implemented into a new VScript library that can be found [Here](https://github.com/potato-tf/VScript-Popfile-Extensions).  This library still needs a ton of work to get as much parity with the extension as possible, but things are moving along.  We encourage everyone to open pull requests to replicate the soon-to-be-doomed features.

As for the CPU usage optimizations and other non-MvM additions, it will likely need to be rewritten into a newer, more stripped down version of the extension if they are still possible.  porting sigmod/rafmod in its entirety to 64bit would likely be impractical and unnecessary.

**Comment by rafradek** [comment]
Once sourcemod 1.12 is stable
