### ISSUE TITLE
[CS:S] Bugs

### ISSUE THREAD

**Issue by hi7k** [rafradek/sigsegv-mvm#49]
sig_perf_sendprop_optimize Bug:

Recently I upgraded to the newest only-optimize version and it has made the props glitch out, In the past sig_perf_sendprop_optimize, wouldn't cause this, an example is on jb_avalanche cell doors (prop_dynamic, named Cell Slider). After the 1st round ends the doors come back, however the floating doors are still there, it seems from A error glitch.
![bug1](https://github.com/rafradek/sigsegv-mvm/assets/136254061/0f297493-44f6-4c30-94e1-9c13c6343420)
![bug2](https://github.com/rafradek/sigsegv-mvm/assets/136254061/9662f44e-ea44-40c9-9aaa-d9bbe6b2b90c)

Invisible weapons:

I've noticed in spectator if someone changes weapon it turns their viewmodel invisible. frequently happens, not always.

![bu3](https://github.com/rafradek/sigsegv-mvm/assets/136254061/5fa9ff75-5804-4c12-a466-4001c1f7ef83)

It still happens sig_perf_sendprop_optimize 0

![image](https://github.com/rafradek/sigsegv-mvm/assets/136254061/762b17ce-587a-4d2a-a178-fd19b8f83456)

**Comment by rafradek** [comment]
Fixed in recent relese
