### ISSUE TITLE
[TF2 x64 Linux] Updating the plugins

### ISSUE THREAD

**Issue by Ranily57** [rafradek/sigsegv-mvm#50]
since TF2 has been updated to x64, thhe plugins doesn't work anymore and make the server crash

**Comment by Alex-gnzl** [comment]
The current tf2 update has ABI fixes that lets the extension load again (on the 32-bit server anyway), but a lot of signatures seem to have changed

**Comment by Ranily57** [comment]
Actually i wait for the compiled version, because for some reasons i have issue compiling the code myself
