### ISSUE TITLE
Reprogrammed Condition, and SpawnTemplate does not works at all.

### ISSUE THREAD

**Issue by kildarewasbanned** [rafradek/sigsegv-mvm#59]
When skipping to wave 6, or any higher wave that spawns templates whenever the mission is loaded, does not seems to spawn the template.
![Screenshot (196)](https://github.com/rafradek/sigsegv-mvm/assets/157809252/62a0fc40-de79-4620-87d4-14617d5adb47)

And Repgrammed Condition does not works.
![Screenshot (199)](https://github.com/rafradek/sigsegv-mvm/assets/157809252/980b416a-09e3-4637-8588-791201f728fd)
The Red bots should spawn here.

**Comment by rafradek** [comment]
I checked mobocracy and templates and red robots spawn fine even on wave 6. Does the entire mission need to be played for the bug to happen?
