### ISSUE TITLE
Sigsegv extension breaks some vscripts of some tf2 maps

### ISSUE THREAD

**Issue by RussiaTails** [rafradek/sigsegv-mvm#60]
Sigsegv extension breaks vscripts, at least, of official map cp_sulfur and community map pl_fountain_b3. In Sulfur it breaks timer for BLU team and it won't end a round after they cap all control points which makes it incompletable until RED timer runs out. In Fountain, a payload stucks in a way completely. The only fix I know is to unload sigsegv extension on these maps but loading it again makes a server to crash

**Comment by rafradek** [comment]
Sulfur issue is fixed. If in other cases it does not work you can unset sig_etc_fast_entity_name_lookup convar

**Comment by RussiaTails** [comment]
Sulfur issue is gone and I appreciate for that. Unfortunately, Fountain still has the same problem, even command sig_etc_fast_entity_name_lookup doesn't do anything for this map. Is there any other commands which may do a trick?
![Удалить](https://github.com/rafradek/sigsegv-mvm/assets/113246593/3c7994db-aa95-40aa-a84a-76d3c787b9d1)

**Comment by rafradek** [comment]
This should be fixed as well now

**Comment by RussiaTails** [comment]
Thanks! Fountain and Sulfur don't have this problem anymore. If I'll find something else I either reply here or make a new issue page, but I hope I won't find any issues in the future

**Comment by RussiaTails** [comment]
I've found what there were other broken zi_ maps with sigsegv. The bug is pretty old but I remembered it just now after I've met up with it again. Whenever a player played as zombie  and after the game they change class as a RED, they will always have negative ammount of ammo
![20240114203048_1](https://github.com/rafradek/sigsegv-mvm/assets/113246593/a15cfc78-7513-4460-ac1c-602c07b3d6e1)

**Comment by rafradek** [comment]
Fixed in new release
