### ISSUE TITLE
TFBot Spies, sapping players, that are non robots.

### ISSUE THREAD

**Issue by kildarewasbanned** [rafradek/sigsegv-mvm#63]
Ever since 64 bits update and new release dropped for rafmod, the TFBot spies are being able to sap non tfbots, and how they do it? they sap an building that if an player is inside of the building or near it, the spy tires to sap the building, but also sapping the player, causing to trigger the sapper power upgrade.
Example: https://drive.google.com/file/d/1R7gvgDWnN4msjibywRY4rW6IGe7oNAm4/preview 

This also applies to every building possible. Doesnt matter what level it is. it'll still sap the player and building, athought they do not sap themselves. they dont get stunned but the sapper is on their head.
Their stats, aint edited aswell to sap players.
![Screenshot (273)](https://github.com/rafradek/sigsegv-mvm/assets/157809252/d67601da-a349-43b0-97cf-a588523574a8)
![image](https://github.com/rafradek/sigsegv-mvm/assets/157809252/b5296fce-feec-4d03-ba9e-283eaf77774c)

Teleporter, and building does works. aswell, but the thing i'm guessing that. the blue robots are stealing code from sapper power upgrade.

**Comment by rafradek** [comment]
Should be fixed
