### ISSUE TITLE
Triggers have halved strength.

### ISSUE THREAD

**Issue by pdaxpert** [rafradek/sigsegv-mvm#67]
I've only noticed it on trigger_hurts and trigger_apply_impulse so far, but it seems like their respective strength value is havled rather than being the value written down in the point template.
The trigger_hurt's damage value appears to be halved (albeit this could be because of server skill? not sure, damagetype doesn't affect it), while trigger_apply_impulse's force value seems to be halved.

**Comment by rafradek** [comment]
trigger_hurt always does half damage written twice per second
