### ISSUE TITLE
Popextensions+ bot pointtemplates are weirdly offset.

### ISSUE THREAD

**Issue by pdaxpert** [rafradek/sigsegv-mvm#68]
I'm not sure by how much they are offset, but it's clearly way off. While rafmod can be used to replace the features, it probably shouldn't be causing this in the first place.
I can confirm that the bot pts from popextent+ work just fine in vanilla, while on a rafmodded server they broke and got weirdly offsetted.

**Comment by rafradek** [comment]
Would need an example of this happening

**Comment by pdaxpert** [comment]
![20240520141224_1](https://github.com/rafradek/sigsegv-mvm/assets/126423907/081b76b2-249a-4b71-a8a7-b9103c378bf2)
![20240520141619_1](https://github.com/rafradek/sigsegv-mvm/assets/126423907/67ec6b70-1070-42d3-9c2c-ee454318cbe7)

The first screenshot is on a rafmodded server, the second one is on vanilla

**Comment by rafradek** [comment]
Can i have the mission/scripts, please?

**Comment by pdaxpert** [comment]
[popextent_test.zip](https://github.com/rafradek/sigsegv-mvm/files/15377052/popextent_test.zip)
here's my test mission & scripts, popextentions+ is excluded but can be obtained [here.](https://github.com/potato-tf/PopExtensionsPlus)

**Comment by rafradek** [comment]
This is an issue of scripts uploaded on the server
