### ISSUE TITLE
PopExt+ Tanks with custom models do not properly display

### ISSUE THREAD

**Issue by Seelpit** [rafradek/sigsegv-mvm#74]
Using PopExtensionsPlus to give tanks custom models, through the AddTankName function, results in the default tank model still displaying:
```js
PopExt.AddTankName("sleightank", {
	Model = {
		Default = "models/bots/boss_bot/robo_sleigh/robo_sleigh.mdl",
		Damage1 = "models/bots/boss_bot/robo_sleigh/robo_sleigh_damage1.mdl",
		Damage2 = "models/bots/boss_bot/robo_sleigh/robo_sleigh_damage2.mdl",
		Damage3 = "models/bots/boss_bot/robo_sleigh/robo_sleigh_damage3.mdl",
	}
```

On a vanilla / listen server, the tank retains its proper model.
Does this have to do with some internal logic that resets tank models if no custom model is specified through rafmod?

**Comment by rafradek** [comment]
I would like to ask for the popfile and scripts

**Comment by rafradek** [comment]
I've noticed that there is a mistake in the pop file. The tanks are named tankboss, you changed the onbombdroppedoutput instead incorrectly

**Comment by Seelpit** [comment]
Oh, wow, that's embarrassing. I could've sworn I tested it properly. Apologies for the false report! I will verify its functionality slightly later today. Closing the issue now.
