### ISSUE TITLE
[Feature Request] Attribute to change damage needed to charge a banner

### ISSUE THREAD

**Issue by luigi64fan** [rafradek/sigsegv-mvm#89]
As the title says, I'm requesting an attribute to change the damage needed to charge a banner.
Admittedly, this is mostly because I've been messing around with custom banners, though it may have niche applications outside of it, such as nerfing or buffing the existing banners for whatever reason people would have to do that.

The applications of this could potentially allow for more potent or less potent custom banners than the usual 400/600 damage banners.
Of course it's up to you if you try to implement this, but it would be appreciated if it was added.

**Comment by talascio** [comment]
`mod rage on hit bonus` and `mod rage on hit penalty` already exist

**Comment by luigi64fan** [comment]
`mod rage on hit bonus/penalty` do not work as a percentage increase or decrease to the rage generated. I'm pretty sure they add that percentage on each hit.
I've tried using higher penalty values and the rage bar sometimes lost progress instead of gaining it.

**Comment by DrCactusTF2** [comment]
rage on hit bonus is good for basically lowering the cap, but rage on hit penalty is extremely finicky and not adequate if you want to make a banner take more damage to charge
